import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";

const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  adjustFontFallback: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dmSans.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <div className="font-base prose-headings:font-heading text-foreground prose-h1:sm:text-[33px] prose-h3:sm:text-xl prose-h3:md:text-2xl prose-h1:text-2xl prose-h2:text-2xl prose-h2:md:text-3xl prose-h3:lg:text-3xl prose-h3:xl:text-3xl prose-h2:lg:text-4xl prose-h2:2xl:text-4xl prose-h3:2xl:text-4xl prose-h1:md:text-5xl prose-h1:xl:text-5xl prose-h1:2xl:text-6xl">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
